# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chroniFic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image_field',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 28, 12, 44, 14, 496091, tzinfo=utc)),
        ),
    ]
