# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chroniFic', '0002_auto_20171020_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chroniFic.Department'),
        ),
    ]
